import type { DesktopAdapter } from "./desktopAdapter";
import {
  approveAndExecuteAcceptActionRequest,
  approveAndExecuteCancelAction,
  approveAndExecuteCompleteAction,
  approveAndExecuteReopenAction,
  approveAndExecuteCloseRisk,
  approveAndExecuteIssueTransition,
  approveAndExecuteRecordRiskOccurrence,
  approveAndExecuteResolveDecisionRequest,
  declineActionRequest,
  linkActionCompletionEvidence,
  linkEvidenceToProduct,
  loadActionCompletionContext,
  loadEvidenceReferences,
  loadExecutiveCockpit,
  loadLedgerStatus,
  loadPeopleDirectory,
  loadPortfolioOverview,
  loadProductDetail,
  loadVaultStatus,
  loadWorkQueue,
  prepareAcceptActionRequest,
  prepareCancelAction,
  prepareCompleteAction,
  prepareReopenAction,
  pinEvidenceFingerprint,
  prepareCloseIssue,
  prepareCloseRisk,
  prepareRecordRiskOccurrence,
  prepareReopenIssue,
  prepareResolveDecisionRequest,
  prepareResolveIssue,
  rejectPreparedAcceptActionRequest,
  rejectPreparedActionIntent,
  rejectPreparedDecisionIntent,
  rejectPreparedIssueIntent,
  rejectPreparedRiskIntent,
  reobserveEvidenceVerification,
  startAction,
  withdrawActionRequest,
  withdrawDecisionRequest,
} from "../routes/ipcCockpit";

/**
 * The production adapter: each method is exactly one Tauri IPC command,
 * through the typed loaders in `ipcCockpit`. Nothing here transforms a
 * result or swallows a rejection; the host's safe error envelope reaches
 * the route as-is.
 */
export const tauriAdapter: DesktopAdapter = {
  loadExecutiveCockpit,
  loadPortfolioOverview,
  loadPeopleDirectory,
  loadWorkQueue,
  loadProductDetail,
  prepareAcceptActionRequest,
  approveAndExecuteAcceptActionRequest,
  rejectPreparedAcceptActionRequest,
  declineActionRequest,
  withdrawActionRequest,
  startAction,
  loadActionCompletionContext,
  linkActionCompletionEvidence,
  prepareCompleteAction,
  prepareCancelAction,
  prepareReopenAction,
  approveAndExecuteCompleteAction,
  approveAndExecuteCancelAction,
  approveAndExecuteReopenAction,
  rejectPreparedActionIntent,
  loadEvidenceReferences,
  withdrawDecisionRequest,
  prepareResolveDecisionRequest,
  approveAndExecuteResolveDecisionRequest,
  rejectPreparedDecisionIntent,
  pinEvidenceFingerprint,
  reobserveEvidenceVerification,
  loadVaultStatus,
  loadLedgerStatus,
  linkEvidenceToProduct,
  prepareRecordRiskOccurrence,
  prepareCloseRisk,
  approveAndExecuteRecordRiskOccurrence,
  approveAndExecuteCloseRisk,
  rejectPreparedRiskIntent,
  prepareResolveIssue,
  prepareCloseIssue,
  prepareReopenIssue,
  approveAndExecuteIssueTransition,
  rejectPreparedIssueIntent,
};
