//! `pmc.projection/v1`: the deterministic, disposable, read-only Markdown
//! projection format for the managed `Product Mission Control/Projections/`
//! subtree. This module covers staged generation only -- no filesystem write, no diff against a currently-published
//! managed root, no H1-Auto/H2a routing, no cancellation/recovery. Every
//! rendered field is one `pmc_domain::projection_source`'s DTOs already
//! carry, which is itself the field-allowlist boundary; this module adds no
//! data source of its own and must never
//! widen a field beyond what those DTOs expose.

use std::collections::{HashMap, HashSet};

use pmc_domain::classification::DataClassification;
use pmc_domain::projection_source::LedgerProjectionSnapshot;
use sha2::{Digest, Sha256};

/// The one visible, generated/read-only notice every projection body
/// carries. Its exact English bytes participate in the payload hash --
/// localization belongs in surrounding UI, not in unpredictably changing
/// generated bytes.
const BANNER: &str = "> [!WARNING] Generated read-only Projection\n\
> This file is generated from Product Ledger. Do not edit it.\n\
> Manual changes are never imported into Product Ledger and may be overwritten after review.\n";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectionRecordType {
    Product,
    Project,
    Action,
    Decision,
    Risk,
    Kpi,
}

impl ProjectionRecordType {
    /// The exact managed-subtree folder name (one of the six accepted
    /// folders).
    #[must_use]
    pub const fn folder_name(self) -> &'static str {
        match self {
            Self::Product => "Products",
            Self::Project => "Projects",
            Self::Action => "Actions",
            Self::Decision => "Decisions",
            Self::Risk => "Risks",
            Self::Kpi => "KPIs",
        }
    }

    /// The canonical `pmc_record_type` schema value.
    #[must_use]
    pub const fn schema_name(self) -> &'static str {
        match self {
            Self::Product => "product",
            Self::Project => "project",
            Self::Action => "action",
            Self::Decision => "decision",
            Self::Risk => "risk",
            Self::Kpi => "kpi",
        }
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

/// A collision-resistant, case-insensitively-safe relative path for one
/// record. IDs are already restricted to ASCII alphanumerics plus `-`/`_`
/// (ledger-wide, see `pmc_domain::value::validate_token`), but two IDs
/// differing only by case can still collide on a case-insensitive Windows
/// filesystem, and a raw ID could coincide with a reserved basename (e.g.
/// `CON`). The path digest -- keyed by a fixed domain separator and the
/// record type, so no two distinct `(type, id)` pairs can collide -- rules
/// both out structurally rather than by allowlisting characters.
#[must_use]
pub fn projection_relative_path(record_type: ProjectionRecordType, record_id: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"pmc-projection-path-v1\0");
    hasher.update(record_type.schema_name().as_bytes());
    hasher.update(b"\0");
    hasher.update(record_id.as_bytes());
    let digest = format!("{:x}", hasher.finalize());
    let short_digest = &digest[..32];
    format!(
        "{}/{record_id}--{short_digest}.md",
        record_type.folder_name()
    )
}

/// Every field this schema version may render. Constructing one of these is
/// itself the projection field-allowlist review -- every value
/// here must already exist on a `pmc_domain::projection_source` DTO.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectionFrontmatter {
    pub record_type: ProjectionRecordType,
    pub record_id: String,
    pub source_revision: u64,
    pub ledger_schema_version: u32,
    pub ledger_revision: u64,
    pub ledger_as_of_utc: String,
    pub classification: DataClassification,
    pub lifecycle: Option<&'static str>,
    /// Sorted, deduplicated `"<type>:<id>"` references, e.g.
    /// `"decision:decision-1"`. Only plain identifiers, never free text.
    pub relationship_refs: Vec<String>,
    pub due_or_observed_at_utc: Option<String>,
    /// Sorted, deduplicated freshness/attention labels. Always empty in
    /// this slice -- no attention/freshness classification exists yet in
    /// any domain read model; the field stays present in the schema
    /// contract rather than silently omitted from it.
    pub attention_labels: Vec<String>,
}

fn render_frontmatter(fields: &ProjectionFrontmatter, payload_hash: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str("---\n");
    out.push_str("pmc_projection_schema: \"pmc.projection/v1\"\n");
    out.push_str("pmc_managed: true\n");
    out.push_str(&format!(
        "pmc_record_type: \"{}\"\n",
        fields.record_type.schema_name()
    ));
    out.push_str(&format!("pmc_record_id: \"{}\"\n", fields.record_id));
    out.push_str(&format!(
        "pmc_source_revision: {}\n",
        fields.source_revision
    ));
    out.push_str(&format!(
        "pmc_ledger_schema_version: {}\n",
        fields.ledger_schema_version
    ));
    out.push_str(&format!(
        "pmc_ledger_revision: {}\n",
        fields.ledger_revision
    ));
    out.push_str(&format!(
        "pmc_ledger_as_of_utc: \"{}\"\n",
        fields.ledger_as_of_utc
    ));
    out.push_str(&format!(
        "pmc_classification: \"{}\"\n",
        fields.classification.as_persisted()
    ));
    if let Some(lifecycle) = fields.lifecycle {
        out.push_str(&format!("pmc_lifecycle: \"{lifecycle}\"\n"));
    }
    if !fields.relationship_refs.is_empty() {
        out.push_str("pmc_relationship_refs:\n");
        for reference in &fields.relationship_refs {
            out.push_str(&format!("  - \"{reference}\"\n"));
        }
    }
    if let Some(due_or_observed_at_utc) = &fields.due_or_observed_at_utc {
        out.push_str(&format!(
            "pmc_due_or_observed_at_utc: \"{due_or_observed_at_utc}\"\n"
        ));
    }
    if !fields.attention_labels.is_empty() {
        out.push_str("pmc_attention_labels:\n");
        for label in &fields.attention_labels {
            out.push_str(&format!("  - \"{label}\"\n"));
        }
    }
    if let Some(hash) = payload_hash {
        out.push_str(&format!("pmc_managed_payload_sha256: \"{hash}\"\n"));
    }
    out.push_str("---\n");
    out.push_str(BANNER);
    out
}

/// One generated file, staged in memory only. `content` is the complete,
/// exact bytes a publisher would later write; nothing here has touched a
/// filesystem.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectionArtifact {
    pub relative_path: String,
    pub frontmatter: ProjectionFrontmatter,
    pub content: Vec<u8>,
    pub managed_payload_sha256: String,
    pub final_file_sha256: String,
}

/// Renders one record's frontmatter into a complete, hashed artifact.
/// Deterministic: identical `fields` always produce identical bytes and
/// hashes, since nothing here reads a clock, a filesystem, or any other
/// non-deterministic source.
#[must_use]
pub fn render_projection_artifact(fields: ProjectionFrontmatter) -> ProjectionArtifact {
    let unhashed_payload = render_frontmatter(&fields, None);
    let managed_payload_sha256 = sha256_hex(unhashed_payload.as_bytes());
    let content = render_frontmatter(&fields, Some(&managed_payload_sha256));
    let final_file_sha256 = sha256_hex(content.as_bytes());
    let relative_path = projection_relative_path(fields.record_type, &fields.record_id);
    ProjectionArtifact {
        relative_path,
        frontmatter: fields,
        content: content.into_bytes(),
        managed_payload_sha256,
        final_file_sha256,
    }
}

/// A staged set of generated artifacts for one Ledger snapshot, sorted by
/// `relative_path` (which groups by folder, then by ID, since the digest
/// suffix never changes ordering within a folder for distinct IDs -- ID
/// comparison is what actually determines order there).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectionArtifactSet {
    pub ledger_schema_version: u32,
    pub ledger_revision: u64,
    pub artifacts: Vec<ProjectionArtifact>,
}

impl ProjectionArtifactSet {
    /// A single digest over the entire manifest (path, type, id, revision,
    /// and both hashes of every artifact, in the set's own deterministic
    /// order) -- a cheap way to tell "did anything in this whole set
    /// change" without comparing every artifact individually.
    #[must_use]
    pub fn aggregate_manifest_digest(&self) -> String {
        let mut hasher = Sha256::new();
        hasher.update(self.ledger_schema_version.to_le_bytes());
        hasher.update(self.ledger_revision.to_le_bytes());
        for artifact in &self.artifacts {
            hasher.update(artifact.relative_path.as_bytes());
            hasher.update([0]);
            hasher.update(artifact.frontmatter.record_type.schema_name().as_bytes());
            hasher.update([0]);
            hasher.update(artifact.frontmatter.record_id.as_bytes());
            hasher.update([0]);
            hasher.update(artifact.frontmatter.source_revision.to_le_bytes());
            hasher.update(artifact.managed_payload_sha256.as_bytes());
            hasher.update([0]);
            hasher.update(artifact.final_file_sha256.as_bytes());
            hasher.update([0]);
        }
        format!("{:x}", hasher.finalize())
    }
}

fn relationship_ref(kind: &str, id: &str) -> String {
    format!("{kind}:{id}")
}

fn sorted_deduplicated(mut values: Vec<String>) -> Vec<String> {
    values.sort();
    values.dedup();
    values
}

/// Generates the complete staged artifact set for one consistent Ledger
/// snapshot. Never writes to a filesystem and never compares against a
/// currently-published managed root -- both are out of this slice's scope.
#[must_use]
pub fn generate_projection_artifact_set(
    snapshot: &LedgerProjectionSnapshot,
) -> ProjectionArtifactSet {
    let ledger_as_of_utc = snapshot.ledger_as_of_utc.to_rfc3339_utc();
    let mut artifacts = Vec::with_capacity(
        snapshot.products.len()
            + snapshot.projects.len()
            + snapshot.actions.len()
            + snapshot.decisions.len()
            + snapshot.risks.len()
            + snapshot.kpis.len(),
    );

    for product in &snapshot.products {
        artifacts.push(render_projection_artifact(ProjectionFrontmatter {
            record_type: ProjectionRecordType::Product,
            record_id: product.id.as_str().to_string(),
            source_revision: product.source_revision.get(),
            ledger_schema_version: snapshot.schema_version,
            ledger_revision: snapshot.ledger_revision,
            ledger_as_of_utc: ledger_as_of_utc.clone(),
            classification: product.classification,
            lifecycle: None,
            relationship_refs: Vec::new(),
            due_or_observed_at_utc: None,
            attention_labels: Vec::new(),
        }));
    }
    for project in &snapshot.projects {
        artifacts.push(render_projection_artifact(ProjectionFrontmatter {
            record_type: ProjectionRecordType::Project,
            record_id: project.id.as_str().to_string(),
            source_revision: project.source_revision.get(),
            ledger_schema_version: snapshot.schema_version,
            ledger_revision: snapshot.ledger_revision,
            ledger_as_of_utc: ledger_as_of_utc.clone(),
            classification: project.classification,
            lifecycle: None,
            relationship_refs: Vec::new(),
            due_or_observed_at_utc: None,
            attention_labels: Vec::new(),
        }));
    }
    for action in &snapshot.actions {
        let mut relationship_refs = vec![relationship_ref(
            "action-request",
            action.source_request_id.as_str(),
        )];
        if let Some(decision_id) = &action.source_decision_id {
            relationship_refs.push(relationship_ref("decision", decision_id.as_str()));
        }
        artifacts.push(render_projection_artifact(ProjectionFrontmatter {
            record_type: ProjectionRecordType::Action,
            record_id: action.id.as_str().to_string(),
            source_revision: action.source_revision.get(),
            ledger_schema_version: snapshot.schema_version,
            ledger_revision: snapshot.ledger_revision,
            ledger_as_of_utc: ledger_as_of_utc.clone(),
            classification: action.classification,
            lifecycle: Some(action.state.as_persisted()),
            relationship_refs: sorted_deduplicated(relationship_refs),
            due_or_observed_at_utc: Some(action.due_at.to_rfc3339_utc()),
            attention_labels: Vec::new(),
        }));
    }
    for decision in &snapshot.decisions {
        let mut relationship_refs = Vec::new();
        if let Some(id) = &decision.supersedes_decision_id {
            relationship_refs.push(relationship_ref("decision", id.as_str()));
        }
        if let Some(id) = &decision.superseded_by_decision_id {
            relationship_refs.push(relationship_ref("decision", id.as_str()));
        }
        artifacts.push(render_projection_artifact(ProjectionFrontmatter {
            record_type: ProjectionRecordType::Decision,
            record_id: decision.id.as_str().to_string(),
            source_revision: decision.source_revision.get(),
            ledger_schema_version: snapshot.schema_version,
            ledger_revision: snapshot.ledger_revision,
            ledger_as_of_utc: ledger_as_of_utc.clone(),
            classification: decision.classification,
            lifecycle: Some(decision.state.as_persisted()),
            relationship_refs: sorted_deduplicated(relationship_refs),
            due_or_observed_at_utc: Some(decision.decided_at.to_rfc3339_utc()),
            attention_labels: Vec::new(),
        }));
    }
    for risk in &snapshot.risks {
        artifacts.push(render_projection_artifact(ProjectionFrontmatter {
            record_type: ProjectionRecordType::Risk,
            record_id: risk.id.as_str().to_string(),
            source_revision: risk.source_revision.get(),
            ledger_schema_version: snapshot.schema_version,
            ledger_revision: snapshot.ledger_revision,
            ledger_as_of_utc: ledger_as_of_utc.clone(),
            classification: risk.classification,
            lifecycle: Some(risk.state.as_persisted()),
            relationship_refs: Vec::new(),
            due_or_observed_at_utc: risk.next_review_at.map(|t| t.to_rfc3339_utc()),
            attention_labels: Vec::new(),
        }));
    }
    for kpi in &snapshot.kpis {
        artifacts.push(render_projection_artifact(ProjectionFrontmatter {
            record_type: ProjectionRecordType::Kpi,
            record_id: kpi.id.as_str().to_string(),
            source_revision: kpi.source_revision.get(),
            ledger_schema_version: snapshot.schema_version,
            ledger_revision: snapshot.ledger_revision,
            ledger_as_of_utc: ledger_as_of_utc.clone(),
            classification: kpi.classification,
            lifecycle: None,
            relationship_refs: Vec::new(),
            due_or_observed_at_utc: None,
            attention_labels: Vec::new(),
        }));
    }

    artifacts.sort_by(|a, b| a.relative_path.cmp(&b.relative_path));

    ProjectionArtifactSet {
        ledger_schema_version: snapshot.schema_version,
        ledger_revision: snapshot.ledger_revision,
        artifacts,
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectionVerificationError {
    /// The recomputed relative path does not match the artifact's own
    /// stored path -- the artifact's `record_type`/`record_id` no longer
    /// agree with where it claims to live.
    PathMismatch { index: usize },
    /// Re-rendering the artifact's own stored frontmatter fields produces
    /// different bytes than `content` actually holds.
    ContentMismatch { index: usize },
    /// The stored `managed_payload_sha256` does not match what the
    /// artifact's own frontmatter fields hash to.
    PayloadHashMismatch { index: usize },
    /// The stored `final_file_sha256` does not match the hash of `content`.
    FinalHashMismatch { index: usize },
}

/// Recomputes every artifact's path and both hashes purely from data already
/// carried on the artifact itself (never re-reading the Ledger), and fails
/// on the first mismatch found. A single mutated byte anywhere in an
/// artifact's `content`, either stored hash, `relative_path`, or any
/// frontmatter field is guaranteed to produce a mismatch, because
/// `render_projection_artifact` is a pure, deterministic function of
/// exactly those fields.
pub fn verify_staged_artifact_set(
    set: &ProjectionArtifactSet,
) -> Result<(), ProjectionVerificationError> {
    for (index, artifact) in set.artifacts.iter().enumerate() {
        let expected_path = projection_relative_path(
            artifact.frontmatter.record_type,
            &artifact.frontmatter.record_id,
        );
        if expected_path != artifact.relative_path {
            return Err(ProjectionVerificationError::PathMismatch { index });
        }
        let recomputed = render_projection_artifact(artifact.frontmatter.clone());
        if recomputed.managed_payload_sha256 != artifact.managed_payload_sha256 {
            return Err(ProjectionVerificationError::PayloadHashMismatch { index });
        }
        if recomputed.final_file_sha256 != artifact.final_file_sha256 {
            return Err(ProjectionVerificationError::FinalHashMismatch { index });
        }
        if recomputed.content != artifact.content {
            return Err(ProjectionVerificationError::ContentMismatch { index });
        }
    }
    Ok(())
}

/// One artifact's manifest-only record -- everything needed to detect
/// whether it changed, without the file's actual bytes. This is the shape a
/// "currently published" manifest is made of, and the shape the Ledger
/// persists after a successful publish.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectionManifestEntry {
    pub relative_path: String,
    pub record_type: ProjectionRecordType,
    pub record_id: String,
    pub source_revision: u64,
    /// The classification the published file carries. Recorded here because
    /// it is the ONLY place a *removed* record's classification can still be
    /// read: once a record leaves the Ledger, the fresh artifact set no
    /// longer contains it, so the H2a preview covering its deletion would
    /// otherwise have no honest classification to bind.
    pub classification: DataClassification,
    pub managed_payload_sha256: String,
    pub final_file_sha256: String,
}

impl ProjectionArtifactSet {
    /// The manifest-only view of this set -- what a publisher would persist
    /// as "what's now published" after a successful write, and what a later
    /// generation diffs a fresh set against.
    #[must_use]
    pub fn manifest_entries(&self) -> Vec<ProjectionManifestEntry> {
        self.artifacts
            .iter()
            .map(|artifact| ProjectionManifestEntry {
                relative_path: artifact.relative_path.clone(),
                record_type: artifact.frontmatter.record_type,
                record_id: artifact.frontmatter.record_id.clone(),
                source_revision: artifact.frontmatter.source_revision,
                classification: artifact.frontmatter.classification,
                managed_payload_sha256: artifact.managed_payload_sha256.clone(),
                final_file_sha256: artifact.final_file_sha256.clone(),
            })
            .collect()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectionArtifactChange {
    Created,
    Updated,
    Removed,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectionChangeSetEntry {
    pub relative_path: String,
    pub record_type: ProjectionRecordType,
    pub record_id: String,
    pub change: ProjectionArtifactChange,
    /// For `Created`/`Updated`, the classification the newly generated file
    /// carries; for `Removed`, the classification the *published* file
    /// carried, read from the baseline manifest. Either way this is the
    /// honest classification of the file this entry acts on, which the H2a
    /// preview must bind (every H2a preview carries a classification, and
    /// `prepared_intents.classification` is NOT NULL).
    pub classification: DataClassification,
}

/// The exact, complete set of files one publish would touch -- never a
/// batch subset of a larger logical change, matching ADR 0007's rule that
/// one logical operation cannot be split to evade H2a approval. Entries are
/// sorted by `relative_path`, matching `ProjectionArtifactSet`'s own order.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectionChangeSet {
    pub entries: Vec<ProjectionChangeSetEntry>,
}

impl ProjectionChangeSet {
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }
}

/// Compares a freshly generated artifact set against what's currently
/// published (a manifest recorded at the last successful publish, or empty
/// for a never-yet-published Vault) and returns exactly what a publish
/// would need to create, update, or remove. Pure: reads neither the
/// Ledger nor a filesystem -- both `fresh` and `published` are already-read
/// data. Unchanged artifacts (identical `final_file_sha256`) produce no
/// entry at all.
///
/// Runs in O(n + m) via hashed path indexes rather than a nested scan.
/// Both inputs happen to arrive sorted today, so a merge walk would also
/// work, but indexing deliberately makes no ordering assumption about
/// `published`: that slice comes from a caller (eventually a SQL read), and
/// a silently unsorted baseline must not be able to turn into a wrong diff
/// -- publishing the wrong file set is exactly the failure ADR 0007 exists
/// to prevent. ADR 0007's ceiling contemplates tens of thousands of files,
/// where the previous nested scan was quadratic.
#[must_use]
pub fn diff_against_published(
    fresh: &ProjectionArtifactSet,
    published: &[ProjectionManifestEntry],
) -> ProjectionChangeSet {
    let published_by_path: HashMap<&str, &ProjectionManifestEntry> = published
        .iter()
        .map(|entry| (entry.relative_path.as_str(), entry))
        .collect();
    let fresh_paths: HashSet<&str> = fresh
        .artifacts
        .iter()
        .map(|artifact| artifact.relative_path.as_str())
        .collect();

    let mut entries = Vec::new();
    for artifact in &fresh.artifacts {
        let change = match published_by_path.get(artifact.relative_path.as_str()) {
            None => ProjectionArtifactChange::Created,
            Some(entry) if entry.final_file_sha256 != artifact.final_file_sha256 => {
                ProjectionArtifactChange::Updated
            }
            Some(_) => continue,
        };
        entries.push(ProjectionChangeSetEntry {
            relative_path: artifact.relative_path.clone(),
            record_type: artifact.frontmatter.record_type,
            record_id: artifact.frontmatter.record_id.clone(),
            change,
            classification: artifact.frontmatter.classification,
        });
    }
    for entry in published {
        if !fresh_paths.contains(entry.relative_path.as_str()) {
            entries.push(ProjectionChangeSetEntry {
                relative_path: entry.relative_path.clone(),
                record_type: entry.record_type,
                record_id: entry.record_id.clone(),
                change: ProjectionArtifactChange::Removed,
                // The record is gone from the Ledger, so the baseline
                // manifest is the only remaining source of truth for what
                // classification the file being deleted actually carried.
                classification: entry.classification,
            });
        }
    }
    entries.sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
    ProjectionChangeSet { entries }
}

/// ADR 0007's accepted, provisional-until-measured H1-Auto ceiling: an
/// incremental change set may automate only if it is estimated at or below
/// both this file count and the paired duration ceiling below. Changing
/// either requires the ADR's own revisit/CR process -- code must not
/// silently loosen them.
pub use pmc_domain::managed_projection_rebuild::{
    MANAGED_PROJECTION_H1_AUTO_MAX_DURATION_MILLIS as PROJECTION_H1_AUTO_MAX_DURATION_MILLIS,
    MANAGED_PROJECTION_H1_AUTO_MAX_FILES as PROJECTION_H1_AUTO_MAX_FILES,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectionH2aReason {
    /// The very first publish, or an explicitly requested full rebuild --
    /// ADR 0007 routes both to H2a regardless of file count.
    InitialOrFullRebuild,
    /// The change set exceeds [`PROJECTION_H1_AUTO_MAX_FILES`].
    ChangeSetTooLarge,
    /// The estimated duration exceeds
    /// [`PROJECTION_H1_AUTO_MAX_DURATION_MILLIS`].
    EstimatedDurationTooLong,
    /// The currently-published copy no longer matches its own last
    /// recorded manifest -- a manual edit (or other tamper) is present, so
    /// automation must not silently overwrite it.
    IntegrityConflict,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectionAutomationEligibility {
    /// The change set is empty -- there is nothing to publish at all,
    /// neither H1-Auto nor H2a applies.
    NoChanges,
    H1Auto,
    H2aRequired(ProjectionH2aReason),
}

/// Classifies one already-computed [`ProjectionChangeSet`] into H1-Auto vs
/// H2a per ADR 0007. Pure and total: every input combination produces
/// exactly one eligibility, and nothing here can be bypassed by a caller
/// supplying a smaller batch, since it always receives the complete change
/// set as one unit (see [`diff_against_published`]'s own contract).
///
/// `estimated_duration_millis` and `integrity_conflict` are supplied by the
/// caller rather than computed here -- real duration measurement and a
/// currently-published-copy integrity check both need to touch the
/// filesystem, which this pure function deliberately does not.
#[must_use]
pub fn classify_projection_automation(
    change_set: &ProjectionChangeSet,
    is_initial_or_full_rebuild: bool,
    estimated_duration_millis: u64,
    integrity_conflict: bool,
) -> ProjectionAutomationEligibility {
    if change_set.is_empty() {
        return ProjectionAutomationEligibility::NoChanges;
    }
    if integrity_conflict {
        return ProjectionAutomationEligibility::H2aRequired(
            ProjectionH2aReason::IntegrityConflict,
        );
    }
    if is_initial_or_full_rebuild {
        return ProjectionAutomationEligibility::H2aRequired(
            ProjectionH2aReason::InitialOrFullRebuild,
        );
    }
    if change_set.len() > PROJECTION_H1_AUTO_MAX_FILES {
        return ProjectionAutomationEligibility::H2aRequired(
            ProjectionH2aReason::ChangeSetTooLarge,
        );
    }
    if estimated_duration_millis > PROJECTION_H1_AUTO_MAX_DURATION_MILLIS {
        return ProjectionAutomationEligibility::H2aRequired(
            ProjectionH2aReason::EstimatedDurationTooLong,
        );
    }
    ProjectionAutomationEligibility::H1Auto
}
